import { Product } from './product';

export const PRODUCTS: Product[] = [
  {
    id: 1000,
    code: "b-max",
    name: "B-Max",
    description: "El Ford B-Max llega para consolidar la fuerza de Ford en el mercado de los monovolúmenes.",
    image: "bamboo-watch.jpg",
    price: 15400,
    category: "Monovolumen",
    quantity: 24,
    rating: 4,
    extras: []
  },
  {
    id: 1001,
    code: "c-max",
    name: "C-Max",
    description: "El Ford C-Max es un monovolumen de cinco plazas, perteneciente al segmento C, con una longitud de 4,38 metros.",
    image: "black-watch.jpg",
    price: 21715,
    category: "Monovolumen",
    quantity: 61,
    rating: 4,
    extras: []
  },
  {
    id: 1002,
    code: "ecosport",
    name: "EcoSport",
    description: "La marca del óvalo lanza al mercado el Ford EcoSport, un nuevo SUV compacto con el que pretende 'dar guerra' en un segmento muy muy competido.",
    image: "blue-band.jpg",
    price: 19835,
    category: "SUV",
    quantity: 2,
    rating: 4,
    extras: []
  },
  {
    id: 1003,
    code: "edge",
    name: "Edge",
    description: "El nuevo Ford Edge es la gran apuesta del fabricante norteamericano para plantar cara en el segmento de los vehículos SUV de corte premium.",
    image: "blue-t-shirt.jpg",
    price: 44575,
    category: "SUV",
    quantity: 25,
    rating: 5,
    extras: []
  },
  {
    id: 1004,
    code: "explorer",
    name: "Explorer",
    description: "El Ford Explorer es un SUV grande que lleva décadas arrasando en Estados Unidos y que, tras muchos años, por fin ha cruzado el charco para comenzar a venderse en Europa.",
    image: "bracelet.jpg",
    price: 79350,
    category: "SUV",
    quantity: 73,
    rating: 5,
    extras: []
  },
  {
    id: 1005,
    code: "fiesta",
    name: "Fiesta",
    description: "El Ford Fiesta va por su séptima generación, conquistando el mercado desde 1976.",
    image: "brown-purse.jpg",
    price: 15145,
    category: "Turismo",
    quantity: 0,
    rating: 4,
    extras: []
  },
  {
    id: 1006,
    code: "focus",
    name: "Focus",
    description: "Ya conocemos la cuarta generación del Ford Focus, el compacto de segmento C de la marca americana.",
    image: "chakra-bracelet.jpg",
    price: 19575,
    category: "Turismo",
    quantity: 5,
    rating: 5,
    extras: []
  },
  {
    id: 1007,
    code: "galaxy",
    name: "Galaxy",
    description: "El Ford Galaxy es un monovolumen del segmento D lanzado por primera vez al mercado en 1995.",
    image: "galaxy-earrings.jpg",
    price: 36750,
    category: "Monovolumen",
    quantity: 23,
    rating: 4,
    extras: []
  },
  {
    id: 1008,
    code: "gt",
    name: "GT",
    description: "El Ford GT es, posiblemente, el deportivo americano por excelencia.",
    image: "game-controller.jpg",
    price: 388000,
    category: "Deportivo",
    quantity: 2,
    rating: 5,
    extras: []
  },
  {
    id: 1009,
    code: "ka",
    name: "Ka+",
    description: "El Ford Ka+ es la alternativa de la marca del óvalo para el segmento de los automóviles urbanos.",
    image: "gaming-set.jpg",
    price: 9725,
    category: "Urbano",
    quantity: 63,
    rating: 4,
    extras: []
  },
  {
    id: 1010,
    code: "kuga",
    name: "Kuga",
    description: "La tercera generación del Ford Kuga fue presentada en 2019 con importantes novedades en materia de tecnología y sistemas de propulsión.",
    image: "gold-phone-case.jpg",
    price: 24900,
    category: "SUV",
    quantity: 0,
    rating: 4,
    extras: []
  },
  {
    id: 1011,
    code: "mondeo",
    name: "Mondeo",
    description: "La nueva generación del Ford Mondeo llega cargada de tecnología, con una amplia oferta de motores y tres carrocerías disponibles.",
    image: "green-earbuds.jpg",
    price: 30171,
    category: "Berlina",
    quantity: 23,
    rating: 4,
    extras: []
  },
  {
    id: 1012,
    code: "mustang",
    name: "Mustang",
    description: "Tras una larga espera de casi 50 años –desde su lanzamiento en 1964-, el Ford Mustang llega a Europa.",
    image: "green-t-shirt.jpg",
    price: 43350,
    category: "Deportivo",
    quantity: 74,
    rating: 5,
    extras: []
  },
  {
    id: 1013,
    code: "puma",
    name: "Puma",
    description: "Se trata de un crossover de 5 puertas con tracción delantera para el uso diario, gracias a su motorización híbrida suave.",
    image: "grey-t-shirt.jpg",
    price: 22110,
    category: "SUV",
    quantity: 0,
    rating: 5,
    extras: []
  },
  {
    id: 1014,
    code: "ranger",
    name: "Ranger",
    description: "El Ford Ranger es el pick-up que la marca estadounidense comercializa en Europa.",
    image: "headphones.jpg",
    price: 30830,
    category: "Pick-up",
    quantity: 8,
    rating: 5,
    extras: []
  },
  {
    id: 1015,
    code: "s-max",
    name: "S-Max",
    description: "El Ford S-Max es un monovolumen producido por el fabricante norteamericano para el mercado europeo.",
    image: "light-green-t-shirt.jpg",
    price: 32575,
    category: "Monovolumen",
    quantity: 34,
    rating: 5,
    extras: []
  }
];
